# Generated by Django 5.0.6 on 2024-07-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactivetools', '0002_carbonfootprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonfootprint',
            name='category',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
