# Generated by Django 5.0.6 on 2024-07-18 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactivetools', '0003_carbonfootprint_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
                ('suggestions', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactivetools.carbonfootprintcategory'),
        ),
    ]
