# Generated by Django 5.0.6 on 2024-07-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactivetools', '0004_carbonfootprintcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonfootprint',
            name='category',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.DeleteModel(
            name='CarbonFootprintCategory',
        ),
    ]
