# Generated by Django 5.0.6 on 2024-07-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuickTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waste",
                    models.CharField(
                        choices=[
                            ("BW", "Bulky Waste"),
                            ("GW", "General Waste"),
                            ("HW", "Hazardous Waste"),
                            ("OW", "Organic Waste"),
                            ("RW", "Recyclable Waste"),
                            ("SW", "Select your Waste"),
                        ],
                        default="SW",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Description", models.TextField(max_length=500)),
                (
                    "Waste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Tips",
                        to="quicktips.quicktip",
                    ),
                ),
            ],
        ),
    ]
