# Generated by Django 5.0.6 on 2024-07-14 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quicktips", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quicktip",
            old_name="waste",
            new_name="waste_choices",
        ),
    ]
