# Generated by Django 5.0.6 on 2024-07-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quicktips", "0002_rename_waste_quicktip_waste_choices"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tips",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="tips",
            old_name="Waste",
            new_name="waste_type",
        ),
        migrations.RemoveField(
            model_name="tips",
            name="Name",
        ),
        migrations.AddField(
            model_name="tips",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Waste-Images/"),
        ),
    ]
