# Generated by Django 5.0.6 on 2024-07-16 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quicktips", "0004_remove_tips_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tips",
            new_name="Tip",
        ),
        migrations.RenameModel(
            old_name="QuickTip",
            new_name="WasteType",
        ),
    ]
