# Generated by Django 3.2.6 on 2024-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/'),
        ),
    ]
