# Generated by Django 5.0.6 on 2024-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="feedback",
            field=models.TextField(max_length=100),
        ),
    ]
