# Generated by Django 5.0.7 on 2024-08-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcomming_events', '0003_recyclingworkshoprsvp_workshopfeedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopfeedback',
            name='event',
        ),
        migrations.RemoveField(
            model_name='workshopfeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='RSVP',
        ),
        migrations.DeleteModel(
            name='WorkshopFeedback',
        ),
    ]
